### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ShotDead7297** [GageGamesHD/AlwaysSpawn#1]
please update

**Comment by GhostMaster1573** [comment]
Updated On my profile

**Comment by TheMasterDuper** [comment]
> please update

Hello little buddy! Sorry, I have been gone from Minecraft for years. I turned myself to developing with Roblox/ LUA. I could try to learn php scripting, but I don't know about it. Thank you for the open issue, I will close this and think about turning to PHP scripting.
